# Generated by Django 3.1.3 on 2020-11-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full time', 'full time'), ('half time', 'half time')], default='', max_length=1000),
            preserve_default=False,
        ),
    ]
