# Generated by Django 3.2.9 on 2021-11-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descraption',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
